language: node_js
node_js:
  - "10.16.0"

sudo: required

services:
  - xvfb
addons:
    chrome: stable
before_script:
  - export DISPLAY=:99.0

os:
  - osx
  - linux

env:
  - NODE_ENV="test"


install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm test

after_success:
  - npm run coverage