language: node_js
node_js:
  - "10.16.0"

matrix:
  include:
  - os: osx
  - os: linux
    services: xvfb

env:
  - NODE_ENV="test"

install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm test --silent

after_success:
  - npm run coverage