language: node_js
node_js:
  - "10.16.0"

os:
  - osx
  - linux

sudo: none

services:
  - xvfb

env:
  - NODE_ENV="test"

install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm test

after_success:
  - npm run coverage